# -*- coding: utf-8 -*-
"""VoiceDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1203pjnyFO_rv3VC63vKJnztAUrRSsxel
"""

import speech_recognition as sr
import pyaudio
r=sr.Recognizer()

with sr.Microphone() as source:
    print('speak something: ')
    audio=r.listen(source,timeout=10)
try:
    text=r.recognize_google(audio)
    print('you said:{}'.format(text))
except:
    print('sorry could not recognize your voice')